### PR TITLE
fix for browser freeze issue

### PR DESCRIPTION
**Pull request by oleggo**

### CODE REVIEW

**Comment by felixb-wix** [comment]
Re posting what Oleg wrote:

I think I can fix this old problem in repluggable that causes editor to freeze
It is one line of code
Btw I, after two years since it was reported, catch it almost every day. And today it happened that I found one specific flow when it happened almost always. I also disabled all my browser plugins, refreshed editor and still could catch it.
I spent some time to trace the place where it is when it is stuck, and despite it was hard to get to the exact point and I went only half the way, I think what I found and what I suggest is safe to do and I tested that the problem doesn't occur anymore.

**Comment by oleggo** [comment]
"_owner" is a link to React Fiber node, and there is no sense to use in props compare. It is also very rich in data and can cause performance issues. Another option would be to exclude all key started with "_".

**Review by itsh01 — CHANGES_REQUESTED** [review]
The general idea make sense, but implementation-wise I see 2 issues:

A. Using `_owner` key is too broad and risky, it looks like a valid props to pass to a component, and not a reserved word
B. Having a fiber node in props does not nessesarily implies equality, consider this scenario:
```tsx
<MyComp 
  customElement={ <MyCustomElement prop={ 1 } /> } 
/>
```
If `prop` changes - we still want to re-render, even though `MyCustomElement` is the same

Bottom line - let's change 2 things:
1. The condition - let's make it `React.isValidElement` instead of assuming a specific key (it also compares to a symbol which would be more strict)
2. The return value - instead of assuming `true`, let's compare the actual element type with reference equality, and continue the deep equality comparison recursion over from there only on the props (comparing its props as we do for all props)

Also, let's add some tests

**Review by itsh01 — APPROVED** [review]
Nice 👍

**Pull request merged**
